<?php
// Call RouteTest::main() if this source file is executed directly.
if (!defined('PHPUnit_MAIN_METHOD')) {
    define('PHPUnit_MAIN_METHOD', 'RouteTest::main');
}

require_once 'PHPUnit/Framework.php';

require_once 'Route.php';

/**
 * Test class for Route.
 * Generated by PHPUnit on 2007-08-20 at 22:01:14.
 */
class RouteTest extends PHPUnit_Framework_TestCase {
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        require_once 'PHPUnit/TextUI/TestRunner.php';

        $suite  = new PHPUnit_Framework_TestSuite('RouteTest');
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown() {
    }
}

// Call RouteTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == 'RouteTest::main') {
    RouteTest::main();
}
?>
